spring.application.name=futinform

sports.api.base-url=${API_FOOTBALL_DATA_BASE_URL}
sports.api.key=${API_KEY}

spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=5m
spring.cache.type=caffeine