spring.application.name=futinform

sports.api.base-url=${API_FOOTBALL_DATA_BASE_URL}
sports.api.key=${API_KEY}

spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=60m
spring.cache.type=caffeine

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
